import type { Book, CirculationRecord, Loan, Student } from "@/lib/types";

const onlineEssay = [
  "Knowledge becomes useful when it moves beyond memory and into practice. A library gives that movement a home: one student discovers an idea, another tests it, and a community learns from what follows.",
  "At a university, reading is not a quiet retreat from the world. It is preparation for entering the world with sharper questions. The best readers pause at a claim, trace its assumptions, and ask what evidence would change their mind.",
  "A strong study habit begins with attention. Choose one clear question before opening a chapter. Write what you already believe, then note what the author adds, contradicts, or leaves unresolved. This turns pages into a conversation rather than a task.",
  "Across disciplines, useful ideas often meet at the edges. A principle from economics may illuminate public health; a method from engineering may strengthen agriculture. Curiosity creates those bridges, and careful reading makes them safe to cross.",
  "The purpose of scholarship is not to collect impressive words. It is to make understanding more accurate, more generous, and more available to others. Every responsible note, citation, and discussion contributes to that shared work.",
].join("\n\n");

export const demoBooks: Book[] = [
  {
    id: "book-african-history",
    slug: "foundations-of-african-history",
    title: "Foundations of African History",
    author: "Ama Serwaa Mensah",
    category: "History",
    isbn: "978-9988-1-1042-3",
    description: "A clear, rigorous introduction to the people, ideas, trade routes, and institutions that shaped the African continent from antiquity to the modern era.",
    format: "both",
    totalCopies: 14,
    availableCopies: 8,
    pages: 328,
    publishedYear: 2024,
    language: "English",
    rating: 4.9,
    borrowCount: 184,
    readTime: "6 hr read",
    accent: "#0B1849",
    onlineContent: onlineEssay,
    featured: true,
  },
  {
    id: "book-engineering-maths",
    slug: "engineering-mathematics",
    title: "Engineering Mathematics",
    author: "Kwabena Osei Boateng",
    category: "Engineering",
    isbn: "978-9988-2-0814-4",
    description: "Applied calculus, vectors, differential equations, and numerical methods explained through practical engineering problems.",
    format: "physical",
    totalCopies: 10,
    availableCopies: 3,
    pages: 512,
    publishedYear: 2023,
    language: "English",
    rating: 4.7,
    borrowCount: 161,
    readTime: "9 hr read",
    accent: "#173B74",
    featured: true,
  },
  {
    id: "book-ghanaian-lit",
    slug: "modern-ghanaian-literature",
    title: "Modern Ghanaian Literature",
    author: "Nana Akua Adom",
    category: "Literature",
    isbn: "978-9988-3-0201-9",
    description: "Essays and readings that explore voice, memory, identity, and social change in modern Ghanaian writing.",
    format: "both",
    totalCopies: 9,
    availableCopies: 5,
    pages: 284,
    publishedYear: 2025,
    language: "English",
    rating: 4.8,
    borrowCount: 147,
    readTime: "5 hr read",
    accent: "#5A1B24",
    onlineContent: onlineEssay,
    featured: true,
    newArrival: true,
  },
  {
    id: "book-data-structures",
    slug: "data-structures-made-clear",
    title: "Data Structures Made Clear",
    author: "Kofi Asare",
    category: "Computing",
    isbn: "978-9988-4-4420-7",
    description: "A visual and practical guide to arrays, trees, graphs, hashing, complexity, and the decisions behind good software.",
    format: "digital",
    totalCopies: 0,
    availableCopies: 0,
    pages: 396,
    publishedYear: 2025,
    language: "English",
    rating: 4.9,
    borrowCount: 133,
    readTime: "7 hr read",
    accent: "#171717",
    onlineContent: onlineEssay,
    newArrival: true,
  },
  {
    id: "book-organic-chem",
    slug: "essential-organic-chemistry",
    title: "Essential Organic Chemistry",
    author: "Dr. Efua K. Nyarko",
    category: "Science",
    isbn: "978-9988-5-1187-2",
    description: "Reaction mechanisms and molecular structure taught with concise explanations, worked examples, and revision prompts.",
    format: "physical",
    totalCopies: 16,
    availableCopies: 11,
    pages: 448,
    publishedYear: 2022,
    language: "English",
    rating: 4.6,
    borrowCount: 125,
    readTime: "8 hr read",
    accent: "#1E5B47",
  },
  {
    id: "book-public-health",
    slug: "public-health-in-practice",
    title: "Public Health in Practice",
    author: "Abena Frimpong",
    category: "Health Sciences",
    isbn: "978-9988-6-0914-9",
    description: "Community-centred approaches to epidemiology, prevention, health communication, and resilient care systems.",
    format: "both",
    totalCopies: 8,
    availableCopies: 2,
    pages: 352,
    publishedYear: 2024,
    language: "English",
    rating: 4.7,
    borrowCount: 119,
    readTime: "6 hr read",
    accent: "#7D3122",
    onlineContent: onlineEssay,
  },
  {
    id: "book-economics",
    slug: "principles-of-economics",
    title: "Principles of Economics",
    author: "Yaw Nkrumah",
    category: "Business",
    isbn: "978-9988-7-7714-6",
    description: "An accessible study of markets, policy, incentives, growth, and the economic choices facing emerging economies.",
    format: "physical",
    totalCopies: 12,
    availableCopies: 6,
    pages: 472,
    publishedYear: 2021,
    language: "English",
    rating: 4.5,
    borrowCount: 108,
    readTime: "8 hr read",
    accent: "#5C4824",
  },
  {
    id: "book-research-methods",
    slug: "research-methods-field-guide",
    title: "Research Methods Field Guide",
    author: "Akosua Bediako",
    category: "Research",
    isbn: "978-9988-8-2019-4",
    description: "From a strong research question to responsible data collection, analysis, citation, and communication.",
    format: "digital",
    totalCopies: 0,
    availableCopies: 0,
    pages: 246,
    publishedYear: 2026,
    language: "English",
    rating: 4.8,
    borrowCount: 96,
    readTime: "4 hr read",
    accent: "#3D285D",
    onlineContent: onlineEssay,
    newArrival: true,
  },
];

const today = new Date();
const isoDaysFromNow = (days: number) => {
  const date = new Date(today);
  date.setDate(today.getDate() + days);
  return date.toISOString();
};

export const demoLoans: Loan[] = [
  { id: "loan-1", bookId: "book-engineering-maths", borrowedAt: isoDaysFromNow(-2), dueAt: isoDaysFromNow(3), status: "active", overduePeriods: 0, fineRatePesewas: 350, fineAmountPesewas: 0, fineOutstandingPesewas: 0 },
  { id: "loan-2", bookId: "book-organic-chem", borrowedAt: isoDaysFromNow(-6), dueAt: isoDaysFromNow(1), status: "due-soon", overduePeriods: 0, fineRatePesewas: 350, fineAmountPesewas: 0, fineOutstandingPesewas: 0 },
  { id: "loan-3", bookId: "book-economics", borrowedAt: isoDaysFromNow(-10), dueAt: isoDaysFromNow(-3), status: "overdue", overduePeriods: 3, fineRatePesewas: 350, fineAmountPesewas: 1050, fineOutstandingPesewas: 1050 },
  { id: "loan-4", bookId: "book-african-history", borrowedAt: isoDaysFromNow(-18), dueAt: isoDaysFromNow(-12), returnedAt: isoDaysFromNow(-13), status: "returned", overduePeriods: 0, fineRatePesewas: 350, fineAmountPesewas: 0, fineOutstandingPesewas: 0 },
];

export const demoStudents: Student[] = [
  { id: "student-1", fullName: "Nana Yaa Owusu", indexNumber: "PS/CSC/23/0142", email: "nana.owusu@st.knust.edu.gh", programme: "BSc Computer Science", activeLoans: 2, status: "active", joinedAt: "2026-01-14" },
  { id: "student-2", fullName: "Kwame Agyeman", indexNumber: "PS/ENG/22/0831", email: "kwame.agyeman@st.knust.edu.gh", programme: "BSc Mechanical Engineering", activeLoans: 1, status: "active", joinedAt: "2025-09-03" },
  { id: "student-3", fullName: "Maame Esi Danso", indexNumber: "PS/PHA/24/0028", email: "esi.danso@st.knust.edu.gh", programme: "Doctor of Pharmacy", activeLoans: 3, status: "active", joinedAt: "2026-02-20" },
  { id: "student-4", fullName: "Kweku Amankwah", indexNumber: "PS/ARC/21/0490", email: "kweku.amankwah@st.knust.edu.gh", programme: "BSc Architecture", activeLoans: 0, status: "suspended", joinedAt: "2025-04-18" },
  { id: "student-5", fullName: "Afia Sarpong", indexNumber: "PS/BA/23/1120", email: "afia.sarpong@st.knust.edu.gh", programme: "BSc Business Administration", activeLoans: 1, status: "active", joinedAt: "2026-03-07" },
];

export const demoCirculation: CirculationRecord[] = [
  { id: "circ-1", studentName: "Nana Yaa Owusu", indexNumber: "PS/CSC/23/0142", bookTitle: "Engineering Mathematics", isbn: "978-9988-2-0814-4", issuedAt: isoDaysFromNow(-2), dueAt: isoDaysFromNow(3), status: "active" },
  { id: "circ-2", studentName: "Maame Esi Danso", indexNumber: "PS/PHA/24/0028", bookTitle: "Essential Organic Chemistry", isbn: "978-9988-5-1187-2", issuedAt: isoDaysFromNow(-6), dueAt: isoDaysFromNow(1), status: "due-soon" },
  { id: "circ-3", studentName: "Kwame Agyeman", indexNumber: "PS/ENG/22/0831", bookTitle: "Principles of Economics", isbn: "978-9988-7-7714-6", issuedAt: isoDaysFromNow(-10), dueAt: isoDaysFromNow(-3), status: "overdue" },
  { id: "circ-4", studentName: "Afia Sarpong", indexNumber: "PS/BA/23/1120", bookTitle: "Foundations of African History", isbn: "978-9988-1-1042-3", issuedAt: isoDaysFromNow(-12), dueAt: isoDaysFromNow(-6), returnedAt: isoDaysFromNow(-7), status: "returned" },
];

export const categoryAccents: Record<string, string> = {
  History: "#0B1849",
  Engineering: "#173B74",
  Literature: "#5A1B24",
  Computing: "#171717",
  Science: "#1E5B47",
  "Health Sciences": "#7D3122",
  Business: "#5C4824",
  Research: "#3D285D",
};
